apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: db-deny-egress
  namespace: pqr
spec:
  podSelector:
    matchLabels:
      app: db
  policyTypes:
    - Egress
  egress:
    - ports:
      - port: 53
        protocol: UDP
      - port: 53
        protocol: TCP
